### ISSUE TITLE
[Discussion] What would make done stand out?

### ISSUE THREAD

**Issue by v3rse** [v3rse/done#2]
@oddoye-david Even though we still have a few TODO items to finish, I've been wondering what feature we could add to make `done` standout amongst the pack of cli todo apps.

This issue is a just a way to track and brainstorm ideas we could implement.

**Comment by v3rse** [comment]
@oddoye-david I think we should work on **Git integration**.

Basically:
- Being able to attach commits to a task
- gitignoring our `database.json` automatically

We could also use Git to track work that has been done on task based on **changes made** and **time added and completed**. I will provide some interesting productivity monitoring.

What do you think?

**ISSUE**: #3

**Comment by v3rse** [comment]
@oddoye-david Another feature we could work on is a system for plugins (like the Git integration bit).

**Comment by oddoye-david** [comment]
@v3rse Sounds like a good idea, the git bit. Dunno how exactly we could do plugins. 

So on the git part, what's the flow you're looking at?

**Comment by v3rse** [comment]
@oddoye-david I'll take each new feature from here and put them into separate issues. I'll then link them to the comments here to make them more organised

**Comment by v3rse** [comment]
@oddoye-david another feature is #4
