### ISSUE TITLE
[Feature] Git Integration

### ISSUE THREAD

**Issue by v3rse** [v3rse/done#3]
# Problem

_done_ is pretty developer centric already (since it only runs in the terminal) so adding some for of git integration is only natural. 

Git pretty much monitors how developers do their work. 

This is just to brainstorm  cool stuff we can do with the information git already provides about our coding task. 

Below are some of my thoughts
# Some enhancements
- [ ] Add `.database.json` to `gitignore` if it's present.
- [ ]  `done git` -- initialise git integration with `done`.  
- [ ] `done git` -- if initialised list all task and commits attached.  
- [ ] `done git commit <task> <message>` -- to commit staged changes and link a task to a commit.  
- [ ] `done` -- should now list all tasks and number of commits attached as part of the usual info.

**Comment by jonluca** [comment]
I worked on it over at #6, let me know what you think!

**Comment by v3rse** [comment]
@jonluca Thanks for the PR! Will take a look at it

**Comment by jonluca** [comment]
Great, let me know :) Thanks!

**Comment by v3rse** [comment]
@jonluca sorry for the delay in reviewing the PR. Took a while because I was tied up with work. Done now. Take a look at the changes I request and I'll merge it once they are those changes are made.
